const openExchangeCurrencies = [
  { symbol: "INR", name: "Indian Rupee", significantDecimalDigits: 2 },
  { symbol: "CNY", name: "Chinese Yuan", significantDecimalDigits: 2 },
  { symbol: "USD", name: "United States Dollar", significantDecimalDigits: 2 },
  { symbol: "EUR", name: "Euro", significantDecimalDigits: 2 },
  { symbol: "JPY", name: "Japanese Yen", significantDecimalDigits: 0 },
  {
    symbol: "GBP",
    name: "British Pound Sterling",
    significantDecimalDigits: 2,
  },
  {
    symbol: "AED",
    name: "United Arab Emirates Dirham",
    significantDecimalDigits: 2,
  },
  { symbol: "AFN", name: "Afghan Afghani", significantDecimalDigits: 2 },
  { symbol: "ALL", name: "Albanian Lek", significantDecimalDigits: 0 },
  { symbol: "AMD", name: "Armenian Dram", significantDecimalDigits: 2 },
  // { symbol: "ANG", name: "Netherlands Antillean Guilder" },
  { symbol: "AOA", name: "Angolan Kwanza", significantDecimalDigits: 2 },
  { symbol: "ARS", name: "Argentine Peso", significantDecimalDigits: 2 },
  { symbol: "AUD", name: "Australian Dollar", significantDecimalDigits: 2 },
  { symbol: "AWG", name: "Aruban Florin", significantDecimalDigits: 2 },
  { symbol: "AZN", name: "Azerbaijani Manat", significantDecimalDigits: 2 },
  {
    symbol: "BAM",
    name: "Bosnia-Herzegovina Convertible Mark",
    significantDecimalDigits: 2,
  },
  { symbol: "BBD", name: "Barbadian Dollar", significantDecimalDigits: 2 },
  { symbol: "BDT", name: "Bangladeshi Taka", significantDecimalDigits: 2 },
  { symbol: "BGN", name: "Bulgarian Lev", significantDecimalDigits: 2 },
  { symbol: "BHD", name: "Bahraini Dinar", significantDecimalDigits: 3 },
  { symbol: "BIF", name: "Burundian Franc", significantDecimalDigits: 0 },
  { symbol: "BMD", name: "Bermudan Dollar", significantDecimalDigits: 2 },
  { symbol: "BND", name: "Brunei Dollar", significantDecimalDigits: 2 },
  { symbol: "BOB", name: "Bolivian Boliviano", significantDecimalDigits: 2 },
  { symbol: "BRL", name: "Brazilian Real", significantDecimalDigits: 2 },
  { symbol: "BSD", name: "Bahamian Dollar", significantDecimalDigits: 2 },
  // { symbol: "BTC", name: "Bitcoin" },
  { symbol: "BTN", name: "Bhutanese Ngultrum", significantDecimalDigits: 2 },
  { symbol: "BWP", name: "Botswanan Pula", significantDecimalDigits: 2 },
  { symbol: "BYN", name: "Belarusian Ruble", significantDecimalDigits: 2 },
  // { symbol: "BYR", name: "Belarusian Ruble (pre-2016)" },
  { symbol: "BZD", name: "Belize Dollar", significantDecimalDigits: 2 },
  { symbol: "CAD", name: "Canadian Dollar", significantDecimalDigits: 2 },
  { symbol: "CDF", name: "Congolese Franc", significantDecimalDigits: 2 },
  { symbol: "CHF", name: "Swiss Franc", significantDecimalDigits: 2 },
  {
    symbol: "CLF",
    name: "Chilean Unit of Account (UF)",
    significantDecimalDigits: 4,
  },
  { symbol: "CLP", name: "Chilean Peso", significantDecimalDigits: 0 },
  // { symbol: "CNH", name: "Chinese Yuan (Offshore)" },
  { symbol: "COP", name: "Colombian Peso", significantDecimalDigits: 2 },
  { symbol: "CRC", name: "Costa Rican Colón", significantDecimalDigits: 2 },
  { symbol: "CUC", name: "Cuban Convertible Peso" }, // Not available in JSON
  { symbol: "CUP", name: "Cuban Peso", significantDecimalDigits: 2 },
  { symbol: "CVE", name: "Cape Verdean Escudo", significantDecimalDigits: 2 },
  { symbol: "CZK", name: "Czech Republic Koruna", significantDecimalDigits: 2 },
  { symbol: "DJF", name: "Djiboutian Franc", significantDecimalDigits: 0 },
  { symbol: "DKK", name: "Danish Krone", significantDecimalDigits: 2 },
  { symbol: "DOP", name: "Dominican Peso", significantDecimalDigits: 2 },
  { symbol: "DZD", name: "Algerian Dinar", significantDecimalDigits: 2 },
  // { symbol: "EEK", name: "Estonian Kroon" },
  { symbol: "EGP", name: "Egyptian Pound", significantDecimalDigits: 2 },
  { symbol: "ERN", name: "Eritrean Nakfa", significantDecimalDigits: 2 },
  { symbol: "ETB", name: "Ethiopian Birr", significantDecimalDigits: 2 },
  { symbol: "FJD", name: "Fijian Dollar", significantDecimalDigits: 2 },
  {
    symbol: "FKP",
    name: "Falkland Islands Pound",
    significantDecimalDigits: 2,
  },
  { symbol: "GEL", name: "Georgian Lari", significantDecimalDigits: 2 },
  // { symbol: "GGP", name: "Guernsey Pound" },
  { symbol: "GHS", name: "Ghanaian Cedi", significantDecimalDigits: 2 },
  { symbol: "GIP", name: "Gibraltar Pound", significantDecimalDigits: 2 },
  { symbol: "GMD", name: "Gambian Dalasi", significantDecimalDigits: 2 },
  { symbol: "GNF", name: "Guinean Franc", significantDecimalDigits: 0 },
  { symbol: "GTQ", name: "Guatemalan Quetzal", significantDecimalDigits: 2 },
  { symbol: "GYD", name: "Guyanaese Dollar", significantDecimalDigits: 2 },
  { symbol: "HKD", name: "Hong Kong Dollar", significantDecimalDigits: 2 },
  { symbol: "HNL", name: "Honduran Lempira", significantDecimalDigits: 2 },
  { symbol: "HRK", name: "Croatian Kuna" }, // Not available in JSON
  { symbol: "HTG", name: "Haitian Gourde", significantDecimalDigits: 2 },
  { symbol: "HUF", name: "Hungarian Forint", significantDecimalDigits: 2 },
  { symbol: "IDR", name: "Indonesian Rupiah", significantDecimalDigits: 2 },
  { symbol: "ILS", name: "Israeli New Sheqel", significantDecimalDigits: 2 },
  // { symbol: "IMP", name: "Manx pound" },
  { symbol: "IQD", name: "Iraqi Dinar", significantDecimalDigits: 3 },
  { symbol: "IRR", name: "Iranian Rial", significantDecimalDigits: 2 },
  { symbol: "ISK", name: "Icelandic Króna", significantDecimalDigits: 0 },
  // { symbol: "JEP", name: "Jersey Pound" },
  { symbol: "JMD", name: "Jamaican Dollar", significantDecimalDigits: 2 },
  { symbol: "JOD", name: "Jordanian Dinar", significantDecimalDigits: 3 },
  { symbol: "KES", name: "Kenyan Shilling", significantDecimalDigits: 2 },
  { symbol: "KGS", name: "Kyrgystani Som", significantDecimalDigits: 2 },
  { symbol: "KHR", name: "Cambodian Riel", significantDecimalDigits: 2 },
  { symbol: "KMF", name: "Comorian Franc", significantDecimalDigits: 0 },
  { symbol: "KPW", name: "North Korean Won", significantDecimalDigits: 2 },
  { symbol: "KRW", name: "South Korean Won", significantDecimalDigits: 0 },
  { symbol: "KWD", name: "Kuwaiti Dinar", significantDecimalDigits: 3 },
  { symbol: "KYD", name: "Cayman Islands Dollar", significantDecimalDigits: 2 },
  { symbol: "KZT", name: "Kazakhstani Tenge", significantDecimalDigits: 2 },
  { symbol: "LAK", name: "Laotian Kip", significantDecimalDigits: 2 },
  { symbol: "LBP", name: "Lebanese Pound", significantDecimalDigits: 2 },
  { symbol: "LKR", name: "Sri Lankan Rupee", significantDecimalDigits: 2 },
  { symbol: "LRD", name: "Liberian Dollar", significantDecimalDigits: 2 },
  { symbol: "LSL", name: "Lesotho Loti", significantDecimalDigits: 2 },
  { symbol: "LYD", name: "Libyan Dinar", significantDecimalDigits: 3 },
  { symbol: "MAD", name: "Moroccan Dirham", significantDecimalDigits: 2 },
  { symbol: "MDL", name: "Moldovan Leu", significantDecimalDigits: 2 },
  { symbol: "MGA", name: "Malagasy Ariary", significantDecimalDigits: 2 },
  { symbol: "MKD", name: "Macedonian Denar", significantDecimalDigits: 2 },
  { symbol: "MMK", name: "Myanma Kyat", significantDecimalDigits: 0 },
  { symbol: "MNT", name: "Mongolian Tugrik", significantDecimalDigits: 2 },
  { symbol: "MOP", name: "Macanese Pataca", significantDecimalDigits: 2 },
  // { symbol: "MRO", name: "Mauritanian Ouguiya (pre-2018)" },
  { symbol: "MRU", name: "Mauritanian Ouguiya", significantDecimalDigits: 2 },
  // { symbol: "MTL", name: "Maltese Lira" },
  { symbol: "MUR", name: "Mauritian Rupee", significantDecimalDigits: 2 },
  { symbol: "MVR", name: "Maldivian Rufiyaa", significantDecimalDigits: 2 },
  { symbol: "MWK", name: "Malawian Kwacha", significantDecimalDigits: 2 },
  { symbol: "MXN", name: "Mexican Peso", significantDecimalDigits: 2 },
  { symbol: "MYR", name: "Malaysian Ringgit", significantDecimalDigits: 2 },
  { symbol: "MZN", name: "Mozambican Metical", significantDecimalDigits: 2 },
  { symbol: "NAD", name: "Namibian Dollar", significantDecimalDigits: 2 },
  { symbol: "NGN", name: "Nigerian Naira", significantDecimalDigits: 2 },
  { symbol: "NIO", name: "Nicaraguan Córdoba", significantDecimalDigits: 2 },
  { symbol: "NOK", name: "Norwegian Krone", significantDecimalDigits: 2 },
  { symbol: "NPR", name: "Nepalese Rupee", significantDecimalDigits: 2 },
  { symbol: "NZD", name: "New Zealand Dollar", significantDecimalDigits: 2 },
  { symbol: "OMR", name: "Omani Rial", significantDecimalDigits: 3 },
  { symbol: "PAB", name: "Panamanian Balboa", significantDecimalDigits: 2 },
  { symbol: "PEN", name: "Peruvian Nuevo Sol", significantDecimalDigits: 2 },
  {
    symbol: "PGK",
    name: "Papua New Guinean Kina",
    significantDecimalDigits: 2,
  },
  { symbol: "PHP", name: "Philippine Peso", significantDecimalDigits: 2 },
  { symbol: "PKR", name: "Pakistani Rupee", significantDecimalDigits: 2 },
  { symbol: "PLN", name: "Polish Zloty", significantDecimalDigits: 2 },
  { symbol: "PYG", name: "Paraguayan Guarani", significantDecimalDigits: 0 },
  { symbol: "QAR", name: "Qatari Rial", significantDecimalDigits: 2 },
  { symbol: "RON", name: "Romanian Leu", significantDecimalDigits: 2 },
  { symbol: "RSD", name: "Serbian Dinar", significantDecimalDigits: 2 },
  { symbol: "RUB", name: "Russian Ruble", significantDecimalDigits: 2 },
  { symbol: "RWF", name: "Rwandan Franc", significantDecimalDigits: 0 },
  { symbol: "SAR", name: "Saudi Riyal", significantDecimalDigits: 2 },
  {
    symbol: "SBD",
    name: "Solomon Islands Dollar",
    significantDecimalDigits: 2,
  },
  { symbol: "SCR", name: "Seychellois Rupee", significantDecimalDigits: 2 },
  { symbol: "SDG", name: "Sudanese Pound", significantDecimalDigits: 2 },
  { symbol: "SEK", name: "Swedish Krona", significantDecimalDigits: 2 },
  { symbol: "SGD", name: "Singapore Dollar", significantDecimalDigits: 2 },
  { symbol: "SHP", name: "Saint Helena Pound", significantDecimalDigits: 2 },
  { symbol: "SLL", name: "Sierra Leonean Leone" }, // No matching data (JSON uses "SLE")
  { symbol: "SOS", name: "Somali Shilling", significantDecimalDigits: 2 },
  { symbol: "SRD", name: "Surinamese Dollar", significantDecimalDigits: 2 },
  { symbol: "SSP", name: "South Sudanese Pound", significantDecimalDigits: 2 },
  // { symbol: "STD", name: "São Tomé and Príncipe Dobra (pre-2018)" },
  {
    symbol: "STN",
    name: "São Tomé and Príncipe Dobra",
    significantDecimalDigits: 2,
  },
  { symbol: "SVC", name: "Salvadoran Colón" }, // Not available in JSON
  { symbol: "SYP", name: "Syrian Pound", significantDecimalDigits: 2 },
  { symbol: "SZL", name: "Swazi Lilangeni", significantDecimalDigits: 2 },
  { symbol: "THB", name: "Thai Baht", significantDecimalDigits: 2 },
  { symbol: "TJS", name: "Tajikistani Somoni", significantDecimalDigits: 2 },
  { symbol: "TMT", name: "Turkmenistani Manat", significantDecimalDigits: 2 },
  { symbol: "TND", name: "Tunisian Dinar", significantDecimalDigits: 3 },
  { symbol: "TOP", name: "Tongan Paʻanga", significantDecimalDigits: 2 },
  { symbol: "TRY", name: "Turkish Lira", significantDecimalDigits: 2 },
  {
    symbol: "TTD",
    name: "Trinidad and Tobago Dollar",
    significantDecimalDigits: 2,
  },
  { symbol: "TWD", name: "New Taiwan Dollar", significantDecimalDigits: 2 },
  { symbol: "TZS", name: "Tanzanian Shilling", significantDecimalDigits: 2 },
  { symbol: "UAH", name: "Ukrainian Hryvnia", significantDecimalDigits: 2 },
  { symbol: "UGX", name: "Ugandan Shilling", significantDecimalDigits: 0 },
  { symbol: "UYU", name: "Uruguayan Peso", significantDecimalDigits: 2 },
  { symbol: "UZS", name: "Uzbekistan Som", significantDecimalDigits: 2 },
  {
    symbol: "VES",
    name: "Venezuelan Bolívar Soberano",
    significantDecimalDigits: 2,
  },
  { symbol: "VND", name: "Vietnamese Dong", significantDecimalDigits: 0 },
  { symbol: "VUV", name: "Vanuatu Vatu", significantDecimalDigits: 0 },
  { symbol: "WST", name: "Samoan Tala", significantDecimalDigits: 2 },
  { symbol: "YER", name: "Yemeni Rial", significantDecimalDigits: 2 },
  { symbol: "ZAR", name: "South African Rand", significantDecimalDigits: 2 },
  // { symbol: "ZMK", name: "Zambian Kwacha (pre-2013)" },
  { symbol: "ZMW", name: "Zambian Kwacha", significantDecimalDigits: 2 },
  // { symbol: "ZWL", name: "Zimbabwean Dollar" },
];

export const currencyData = openExchangeCurrencies.map((currency) => {
  let flagClass = `fflag fflag-${currency.symbol.substring(
    0,
    2
  )} ff-xl ff-round`;

  // Check for specific cases where symbols start with 'BT' and handle them differently
  if (currency.symbol === "BTN") {
    flagClass = "fflag fflag-BT ff-xl ff-round"; // Change the class for BTN
  } else if (currency.symbol === "BTC") {
    flagClass = "btcflag ff-xl ff-round"; // Change the class for BTC
  }

  return {
    symbol: currency.symbol,
    name: currency.name,
    flagClass: flagClass,
  };
});

export const significantDigitsFromTicker = (
  ticker: string
): number => {

  return openExchangeCurrencies.find((curr) => curr.symbol === ticker)
    ?.significantDecimalDigits??2;
};
