import { useExpenseStore } from "@/components/ExpenseForm/formStore/formStore";
import { useShallow } from "zustand/react/shallow";

export const useExpenseFormStore = () =>
  useExpenseStore(
    useShallow((state) => ({
      amount: state.amount,
      description: state.description,
      currencySymbol: state.currencySymbol,
      expenseTime: state.expenseTime,
      labels: state.labels,
      location: state.location,
      amountError: state.amountError,
      showAmountError: state.showAmountError,
      participantsError: state.participantsError,
      payersError: state.payersError,
      descriptionError: state.descriptionError,
      isSubmitting: state.isSubmitting,
      participantsByCategory: state.participantsByCategory,
      payersByCategory: state.payersByCategory,
      userMemberId: state.userMemberId,
      participantsCategory: state.participantsCategory,
      payersCategory: state.payersCategory,
      updateParticipantsInCategory: state.updateParticipantsInCategory,
      updatePayersInCategory: state.updatePayersInCategory,
      setParticipantsByCategory: state.setParticipantsByCategory,
      setPayersByCategory: state.setPayersByCategory,
      makePersonalClicked: state.makePersonalClicked,
      showPicker: state.showPicker,
      setMakePersonalClicked: state.setMakePersonalClicked,
      setShowPicker: state.setShowPicker,
      setAmount: state.setAmount,
      setDescription: state.setDescription,
      setCurrencySymbol: state.setCurrencySymbol,
      setExpenseTime: state.setExpenseTime,
      setLabels: state.setLabels,
      setLocation: state.setLocation,
      setAmountError: state.setAmountError,
      setShowAmountError: state.setShowAmountError,
      setParticipantsError: state.setParticipantsError,
      setPayersError: state.setPayersError,
      setDescriptionError: state.setDescriptionError,
      setIsSubmitting: state.setIsSubmitting,
      initialize: state.initialize,
      updateMembers: state.updateMembers,
      validateForm: state.validateForm,
      submitExpense: state.submitExpense,
    }))
  );
