name: Bump Version

on:
  push:
    branches:
      - master

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Bump version patch
        run: |
          npm version patch -m "chore(release): bump version to %s"
          git push --follow-tags