name: Bump Version

on:
  push:
    branches:
      - master

run-name: Bump Version

permissions:
  contents: write
 
jobs:
  version-bump:
    name: Bump Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.DEPLOY_KEY }}
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Bump version patch
        run: |
          git config --local user.email "github-actions@github.com"
          git config --local user.name "GitHub Actions"
          npm config set tag-version-prefix ''
          npm version patch --tag-version-prefix="" -m "Version bump to %s [skip ci]"
          git push --follow-tags