name: Bump Version

on:
  push:
    branches:
      - master
 
jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Set git config as GitHub Actions bot
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
      - name: Bump version patch
        run: |
          npm config set tag-version-prefix ''
          npm version patch --tag-version-prefix="" -m "Version bump to %s [skip ci]"
      - name: Push changes using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git push --force --follow-tags