name: Bump Version

on:
  push:
    branches:
      - master
 
jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.ACTIONS_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '23'
      - name: Set git config
        run: |
          git config --local user.email "projectsplit-admin@users.noreply.github.com"
          git config --local user.name "projectsplit-admin"
      - name: Bump version patch
        run: |
          npm config set tag-version-prefix ''
          npm version patch --tag-version-prefix="" -m "Version bump to %s [skip ci]"
          git push --follow-tags