name: Deploy to production

on:
  release:
    types: [published]
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Install dependencies
        run: npm install

      - name: Setup .env.production
        run: echo "${{ env.ENV_PRODUCTION }}" > .env.production

      - name: Build React App
        run: npm run build-prod
        
      - name: List output of dist directory
        run: ls -alh ${{ github.workspace }}/dist/
            
      - name: Upload dist content via scp
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.SERVER_HOST }}
          USERNAME: ${{ secrets.SERVER_USER }}
          PORT: ${{ secrets.SERVER_SSH_PORT }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
          source: "${{ github.workspace }}/dist/"
          target: "/home/user/split-production/webapp"
          strip_components: 3